name: ghcr-retention

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 3 * * 0"

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old untagged image versions
        uses: actions/delete-package-versions@v5
        with:
          package-type: container
          package-name: ${{ github.event.repository.name }}
          delete-only-untagged-versions: "true"
          min-versions-to-keep: 3
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old non-release tags (keep semver + latest + caches)
        uses: actions/delete-package-versions@v5
        with:
          package-type: container
          package-name: ${{ github.event.repository.name }}
          min-versions-to-keep: 3
          ignore-versions: '^(latest|buildcache|buildcache-pr|\d+\.\d+\.\d+|\d+\.\d+|\d+)$'
          token: ${{ secrets.GITHUB_TOKEN }}
